# spring:
#   config:
#     activate:
#       on-profile: test

# springdoc:
#   api-docs:
#     enabled: true
#   swagger-ui:
#     enabled: true
# openapi:
#   service:
#     api-docs: api-service
#     server: http://127.0.0.1:8082/
#     title: API Document
#     version: 1.0.0